# Generated by Django 2.2.24 on 2023-02-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20230209_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ngouser',
        ),
    ]
