# Generated by Django 2.2.24 on 2023-02-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230121_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canteen',
        ),
    ]
